name: ubuntu-latest

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install test dependencies
        run: |
          Rscript -e "install.packages(c('testthat', 'lavaan', 'devtools'));devtools::install_github("LabAsim/lavaanPlot", force = T)"
      - name: Load libraries
        run: |
          Rscript -e "library(testthat);library(lavaan);library(lavaanPlot)"
      - name: Run tests
        run: |
          Rscript -e "test_dir('tests/testthat')"
