name: ubuntu-latest

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install test dependencies
        run: |
          Rscript -e "install.packages('testthat');install.packages('lavaan')"
      - name: Run tests
        run: |
          Rscript -e "library(testthat);library(lavaan); test_dir('tests/testthat')"
